### ISSUE TITLE
Could not install conda environment on OS X

### ISSUE THREAD

**Issue by ellenkoenig** [sotte/pytorch_tutorial#2]
Hi Stefan, 

first of all, thanks for providing the install instruction for the tutorial in advance :-)
However, I am struggling to install the dependencies on Mac OS X (e.g. the libgcc-ng package). Does the tutorial only work on Linux?

**Comment by ellenkoenig** [comment]
After some hacking around, I got it to install and I can at least download the data and run the first jupyter lab notebook. Maybe the following helps some other OS X user.

Here is the `environment.yml` that I ended up with
```
name: pydata_pytorch_tutorial
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - pip:
    - arrow==0.12.1
    - attrs==17.4.0
    - binaryornot==0.4.4
    - black==18.4a2
    - blessings==1.6.1
    - bpython==0.17.1
    - chardet==3.0.4
    - click==6.7
    - cookiecutter==1.6.0
    - curtsies==0.3.0
    - django==1.11.13
    - django-embed-video==1.1.2
    - easy-thumbnails==2.5
    - ffind==1.2.0
    - flake8==3.5.0
    - future==0.16.0
    - gdata==2.0.18
    - greenlet==0.4.13
    - httpie==0.9.9
    - idna==2.6
    - jinja2-time==0.2.0
    - lxml==4.2.1
    - mccabe==0.6.1
    - pelper==0.1.0
    - pew==1.1.2
    - pipenv==11.10.0
    - poyo==0.4.1
    - pycodestyle==2.3.1
    - pyflakes==1.6.0
    - pyperclip==1.6.0
    - requests==2.18.4
    - torch==0.4.0
    - torchvision==0.2.1
    - typing==3.6.4
    - urllib3==1.22
    - virtualenv==15.1.0
    - virtualenv-clone==0.2.6
    - whichcraft==0.4.1
    - certifi==2018.4.16
    - ipywidgets==7.2.1

  - conda:
    - openblas==0.2.20
    - nodejs
    - pip==9.0.3
    - tqdm==4.23.4
    - backcall==0.1.0
    - blas
    - bleach==2.1.3
    - ca-certificates==2018.03.07
    - cffi==1.11.5
    - cycler==0.10
    - cython==0.28.3
    - dbus==1.13.2
    - decorator==4.3.0
    - entrypoints==0.2.3
    - expat==2.2.5
    - fontconfig==2.12.6
    - freetype
    - glib==2.56.1
    - gmp==6.1.2
    - gst-plugins-base
    - gstreamer
    - html5lib==1.0.1
    - icu==58.2
    - intel-openmp==2018.0.0
    - ipykernel==4.8.2
    - ipython==6.3.1
    - ipython_genutils==0.2.0
    - jedi==0.12.0
    - jinja2==2.10
    - jpeg==9b
    - jsonschema==2.6.0
    - jupyter==1.0.0
    - jupyter_client==5.2.3
    - jupyter_console==5.2.0
    - jupyter_core==4.4.0
    - jupyterlab==0.32.1
    - jupyterlab_launcher==0.10.5
    - kiwisolver==1.0.1
    - libedit==3.1
    - libffi==3.2.1
    - libgcc
    - libgfortran
    - libgfortran-ng
    - libpng==1.6.34
    - libsodium==1.0.16
    - libtiff==4.0.9
    - libxcb==1.13
    - libxml2==2.9.8
    - markupsafe==1.0
    - matplotlib==2.2.2
    - mistune==0.8.3
    - mkl==2018.0.2
    - mkl_fft==1.0.1
    - mkl_random==1.0.1
    - nbconvert==5.3.1
    - nbformat==4.4.0
    - ncurses==6.0
    - ninja==1.8.2
    - notebook==5.4.1
    - numpy==1.14.2
    - olefile==0.45.1
    - openssl==1.0.2o
    - pandoc==1.19.2.1
    - pandocfilters==1.4.2
    - parso==0.2.0
    - pcre==8.42
    - pexpect==4.5.0
    - pickleshare==0.7.4
    - pillow==5.1.0
    - prompt_toolkit==1.0.15
    - ptyprocess==0.5.2
    - pycparser==2.18
    - pygments==2.2.0
    - pyparsing==2.2.0
    - pyqt==5.9.2
    - python==3.6.5
    - python-dateutil==2.7.2
    - pytz==2018.4
    - pyzmq==17.0.0
    - qt==5.9.5
    - qtconsole==4.3.1
    - readline==7.0
    - scikit-learn==0.19.1
    - scipy
    - send2trash==1.5.0
    - setuptools==39.1.0
    - simplegeneric==0.8.1
    - sip==4.19.8
    - six==1.11.0
    - sqlite==3.23.1
    - terminado==0.8.1
    - testpath==0.3.1
    - tk==8.6.7
    - tornado==5.0.2
    - traitlets==4.3.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - wheel==0.31.0
    - widgetsnbextension==3.2.1
    - xz==5.2.3
    - zeromq==4.2.5
    - zlib==1.2.11
    - torchvision
    - pytorch
```

On top of that, I needed to run
`conda update freetype matplotlib` due to some version conflict when importing matplotlib.

I still get an error in the imports though: `ModuleNotFoundError: No module named 'ppt'`I can't find a related package by googling either. Where does that import come from?
